// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqripfhjyzaldcgvkzco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcmlwZmhqeXphbGRjZ3ZremNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTQwOTgsImV4cCI6MjA2MzQzMDA5OH0.yq040oqNeUpiMlOmLHPGiOqUPICCoA88h0mgp_sUu20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});